# Auto-build and push Docker image on push to main branch
name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read                   # for checkout
      packages: write                  # to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- GitHub Container Registry login ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Build and push to GHCR ---
      - name: Build and push to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/llm_to_remarkable:latest

      # --- (Optional) Docker Hub login & push ---
      # To use Docker Hub instead, uncomment the steps below and
      # set DOCKERHUB_USERNAME and DOCKERHUB_TOKEN in your repo Secrets.
      #
      #- name: Log in to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    registry: docker.io
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      #- name: Build and push to Docker Hub
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    push: true
      #    tags: |
      #      ${{ secrets.DOCKERHUB_USERNAME }}/llm_to_remarkable:latest

